sudo: false
language: c
compiler: gcc
dist: trusty

cache:
  directories:
    - perl5
    - dl

env:
  global:
    - TESTNGINX_VER=12152a5
    - PATH=$TRAVIS_BUILD_DIR/bin:$TRAVIS_BUILD_DIR/nginx/objs:$PATH
  matrix:
    - NGINX_VERSION=1.9.15
    - NGINX_VERSION=1.11.13
    - NGINX_VERSION=1.12.2
    - NGINX_VERSION=1.13.8

before_install:
  - curl --version
  - mkdir -p {bin,dl}
  - if [ ! -f dl/nginx-${NGINX_VERSION}.tar.gz ]; then curl -o dl/nginx-${NGINX_VERSION}.tar.gz -L http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz; fi
  - if [ ! -f dl/test-nginx-${TESTNGINX_VER}.tar.gz ]; then curl -o dl/test-nginx-${TESTNGINX_VER}.tar.gz -L "https://github.com/openresty/test-nginx/archive/${TESTNGINX_VER}.tar.gz"; fi
  - if [ ! -f dl/cpanm ]; then curl -o dl/cpanm https://cpanmin.us/; chmod +x dl/cpanm; fi
  - cp dl/cpanm bin/cpanm
  - tar -zxvf dl/nginx-${NGINX_VERSION}.tar.gz && mv nginx-${NGINX_VERSION} nginx
  - cpanm --notest --local-lib=perl5 local::lib && eval $(perl -I perl5/lib/perl5/ -Mlocal::lib)
  - cpanm --notest dl/test-nginx-${TESTNGINX_VER}.tar.gz
  - cpanm --notest Test::File
  - cpanm --notest URI::Query
  - cd nginx
  - ./configure --with-http_v2_module --with-http_ssl_module --add-module=..
  - make
  - cd ..

script:
  - prove -r t
